# file generated by vcs-versioning
# don't change, don't track in version control
from __future__ import annotations

__all__ = [
    "__version__",
    "__version_tuple__",
    "version",
    "version_tuple",
    "__commit_id__",
    "commit_id",
]

version: str
__version__: str
__version_tuple__: tuple[int | str, ...]
version_tuple: tuple[int | str, ...]
commit_id: str | None
__commit_id__: str | None

__version__ = version = '10.2.0.dev37+g964c1345c.d20260611'
__version_tuple__ = version_tuple = (10, 2, 0, 'dev37', 'g964c1345c.d20260611')

__commit_id__ = commit_id = 'g964c1345c'
